Added vikas5914/steam-auth
scholtzm/awesome-steam pull request #10
Opened 2017-06-13 10:18 UTC by vikas5914

Added Vikas5914/steam-auth

Alternative PHP Steam Authentication and user detail package with Composer support

2017-06-13 15:53 UTC, andrewda requested changes

2017-06-13 15:53 UTC, andrewda commented on README.md
> +- [steam-auth](https://github.com/vikas5914/steam-auth) - Alternative PHP Steam Authentication with Composer Support
Use normal sentence capitalization, not title capitalization. Also add a period. Maybe something like:

> An alternative Steam authentication library with Composer support.

2017-06-14 05:03 UTC, vikas5914 commented
Done

2017-06-14 05:07 UTC, andrewda approved these changes

2017-06-14 07:11 UTC, merged

2017-06-14 07:12 UTC, scholtzm commented
Thank you @vikas5914 for contributing and @andrewda for reviewing!